### ISSUE TITLE
更改最近七天的显示为中文

### ISSUE THREAD

**Issue by nobiyou** [freejishu/StatusLive#1]
`var data_list = data.days;
            var data_list = data_list.toString();
            var data_mm ={Jan:"1月",Feb:"2月",Mar:"3月",Apr:"4月",May:"5月",Jun:"6月",Jul:"7月",Aug:"8月",Spt:"9月",Oct:"10月",Nov:"11月",Dec:"12月"};
            var re = new RegExp(Object.keys(data_mm).join("|"),"gi");
            data_list = data_list.replace(re, function(matched){
                  return data_mm[matched];
                });
            data_list = data_list.split(',');
            //console.log(data_list);
            var data_table = "",
                data_table_other = "";
            //for (var i = 0; i < data.days.length; i++) {
            //    data_table = data_table + '<span class="table-status-item">' + data.days[i] + "</span>";
            //}
            for (var i = 0; i < data_list.length; i++) {
				var month = data_list[i].substr(-2);
				var day = data_list[i].substr(0,2);
                data_table = data_table + '<span class="table-status-item">' + month + day + '日' + "</span>";
            }`

**Comment by nobiyou** [comment]
var data_list = data.days;
            var data_list = data_list.toString();
            var data_mm ={Jan:"1月",Feb:"2月",Mar:"3月",Apr:"4月",May:"5月",Jun:"6月",Jul:"7月",Aug:"8月",Spt:"9月",Oct:"10月",Nov:"11月",Dec:"12月"};
            var re = new RegExp(Object.keys(data_mm).join("|"),"gi");
            data_list = data_list.replace(re, function(matched){
                  return data_mm[matched];
                });
            data_list = data_list.split(',');
            //console.log(data_list);
            var data_table = "",
                data_table_other = "";
            //for (var i = 0; i < data.days.length; i++) {
            //    data_table = data_table + '<span class="table-status-item">' + data.days[i] + "</span>";
            //}
            for (var i = 0; i < data_list.length; i++) {
				var month = data_list[i].substr(-2);
				var day = data_list[i].substr(0,2);
                data_table = data_table + '<span class="table-status-item">' + month + day + '日' + "</span>";
            }

**Comment by nobiyou** [comment]
`var data_list = data.days;
            var data_list = data_list.toString();
            var data_mm ={Jan:"1月",Feb:"2月",Mar:"3月",Apr:"4月",May:"5月",Jun:"6月",Jul:"7月",Aug:"8月",Spt:"9月",Oct:"10月",Nov:"11月",Dec:"12月"};
            var re = new RegExp(Object.keys(data_mm).join("|"),"gi");
            data_list = data_list.replace(re, function(matched){
                  return data_mm[matched];
                });
            data_list = data_list.split(',');
            //console.log(data_list);
            var data_table = "",
                data_table_other = "";
            //for (var i = 0; i < data.days.length; i++) {
            //    data_table = data_table + '<span class="table-status-item">' + data.days[i] + "</span>";
            //}
            for (var i = 0; i < data_list.length; i++) {
				var month = data_list[i].substr(-2);
				var day = data_list[i].substr(0,2);
                data_table = data_table + '<span class="table-status-item">' + month + day + '日' + "</span>";
            }`

**Comment by freejishu** [comment]
![Snipaste_2019-03-03_09-57-14.png](https://i.loli.net/2019/03/03/5c7b35760c7a5.png)
做了一下预览，但是发现效果不如之前的好。相对比较，之前的英文字母更简洁一些。
