### ISSUE TITLE
【建议】优化主界面的状态日志

### ISSUE THREAD

**Issue by Tiper-In-Github** [freejishu/StatusLive#12]
主界面的状态日志目前是只要访问了，就会显示全部日志，这种情况下，页面容易过大，且一次性显示所有的日志视乎也不合理，希望就行改进

**Comment by freejishu** [comment]
前一阵子太忙了，最近才看到
建议很好，下次更新处理一下wwww感谢

**Comment by Tiper-In-Github** [comment]
您好，欢迎您致信火毅网络团队。当前人工忙，稍后我们会查看您发的邮件，谢谢合作。--------友情链接----------官方导航站

**Comment by freejishu** [comment]
https://github.com/freejishu/StatusLive/releases/tag/v2.1
v2.1版本优化了日志，支持分页和设定拉取过去 X 天的日志。本issue closed。
