### ISSUE TITLE
请问下名称那怎么加长

### ISSUE THREAD

**Issue by SuiYue124** [freejishu/StatusLive#35]
稍微长一点的名称就换行了，怎么解决。

**Comment by freejishu** [comment]
此处暂无参数；考虑到实际效果，暂时不对名称列进行拓宽；
可拉取代码分支后，修改此处的min-width；后可重新进行编译。
https://github.com/freejishu/StatusLive/blob/ac393a70c093a55b27faa80c206cca09cd4378d2/src/views/Home.vue#L73
